version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: dormitory_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: dormitory
      MYSQL_USER: dormitory_user
      MYSQL_PASSWORD: dormitory_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: